export const THEMES = {
  // ─── FREE ──────────────────────────────────────────────────────────
  midnight: {
    id: 'midnight',
    label: 'Midnight',
    description: 'Deep purple night sky. Classic & elegant.',
    mascot: '🌙',
    premium: false,
    price: 0,
    gradient: ['#1E193A', '#120F27'] as const,
    bg: '#120F27',
    surface: '#1E193A',
    card: '#282247',
    accent: '#7B62FF',
    accentSoft: '#7B62FF22',
    alt: '#46DCB0',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#F5F2FF',
    subtext: '#A6A1C6',
    tab: '#0E0B21',
    divider: 'rgba(255,255,255,0.08)',
    white: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.4)',
  },
  daylight: {
    id: 'daylight',
    label: 'Daylight',
    description: 'Fresh and clean. Perfect for productivity.',
    mascot: '☀️',
    premium: false,
    price: 0,
    gradient: ['#FFFFFF', '#F3F5FB'] as const,
    bg: '#F3F5FB',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    accent: '#387DF7',
    accentSoft: '#387DF722',
    alt: '#20BF8A',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#191A2D',
    subtext: '#757898',
    tab: '#FFFFFF',
    divider: 'rgba(0,0,0,0.07)',
    white: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.10)',
  },
  blossom: {
    id: 'blossom',
    label: 'Blossom',
    description: 'Soft pink petals. Sweet and minimal.',
    mascot: '🌷',
    premium: false,
    price: 0,
    gradient: ['#FFFFFF', '#FEF6F9'] as const,
    bg: '#FEF6F9',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    accent: '#D84080',
    accentSoft: '#D8408022',
    alt: '#5DBD97',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#260F1F',
    subtext: '#8B697A',
    tab: '#FFFFFF',
    divider: 'rgba(0,0,0,0.07)',
    white: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.10)',
  },

  // ─── PREMIUM ────────────────────────────────────────────────────────
  matchaBear: {
    id: 'matchaBear',
    label: 'Matcha Bear',
    description: 'Cozy Japanese cafe vibes. Warm forest greens.',
    mascot: '🐻',
    premium: true,
    price: 49,
    gradient: ['#1E3A14', '#0B1A08'] as const,
    bg: '#0B1A08',
    surface: '#152410',
    card: '#1C3016',
    accent: '#72C84A',
    accentSoft: '#72C84A22',
    alt: '#F0B840',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#D8EDD0',
    subtext: '#78A86A',
    tab: '#080F06',
    divider: 'rgba(114,200,74,0.12)',
    white: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.5)',
  },
  sakuraNight: {
    id: 'sakuraNight',
    label: 'Sakura Night',
    description: 'Cherry blossoms under the stars. Japanese kawaii.',
    mascot: '🌸',
    premium: true,
    price: 49,
    gradient: ['#3A1050', '#10061A'] as const,
    bg: '#10061A',
    surface: '#1E0C30',
    card: '#2A1244',
    accent: '#FF6B9D',
    accentSoft: '#FF6B9D22',
    alt: '#C084FC',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#FFE8F4',
    subtext: '#C090B0',
    tab: '#0C0416',
    divider: 'rgba(255,107,157,0.12)',
    white: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.5)',
  },
  oceanBuddy: {
    id: 'oceanBuddy',
    label: 'Ocean Buddy',
    description: 'Deep sea glow. Bioluminescent & calm.',
    mascot: '🐬',
    premium: true,
    price: 49,
    gradient: ['#0A2A4A', '#040C18'] as const,
    bg: '#040C18',
    surface: '#081A2E',
    card: '#0D2840',
    accent: '#00CFFF',
    accentSoft: '#00CFFF22',
    alt: '#00FFB2',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#C0EEFF',
    subtext: '#5A9CBE',
    tab: '#030910',
    divider: 'rgba(0,207,255,0.12)',
    white: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.5)',
  },
  candyPop: {
    id: 'candyPop',
    label: 'Candy Pop',
    description: 'Sugary sweet rainbow energy. Fun & playful.',
    mascot: '🍭',
    premium: true,
    price: 49,
    gradient: ['#FFB3E8', '#FFF0FA'] as const,
    bg: '#FFF0FA',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    accent: '#FF2D9E',
    accentSoft: '#FF2D9E18',
    alt: '#9B4DFF',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#1A0030',
    subtext: '#9966AA',
    tab: '#FFFFFF',
    divider: 'rgba(255,45,158,0.10)',
    white: '#FFFFFF',
    shadow: 'rgba(255,45,158,0.15)',
  },
  neonGalaxy: {
    id: 'neonGalaxy',
    label: 'Neon Galaxy',
    description: 'Cyberpunk space. Electric neon on pure black.',
    mascot: '⚡',
    premium: true,
    price: 49,
    gradient: ['#151530', '#030308'] as const,
    bg: '#030308',
    surface: '#0A0A18',
    card: '#12122A',
    accent: '#00FF88',
    accentSoft: '#00FF8822',
    alt: '#FF0080',
    warn: '#FF9040',
    danger: '#FF5C5C',
    text: '#EEEEFF',
    subtext: '#7777AA',
    tab: '#020205',
    divider: 'rgba(0,255,136,0.12)',
    white: '#FFFFFF',
    shadow: 'rgba(0,255,136,0.2)',
  },
} as const;

export type ThemeId = keyof typeof THEMES;
export type Theme = typeof THEMES.midnight;

export const CATEGORY_COLORS = {
  Work:    '#7B62FF',
  Health:  '#46DCB0',
  Errand:  '#FF9040',
  Social:  '#A45CF0',
  Travel:  '#40B4FF',
  Other:   '#888888',
} as const;

export type Category = keyof typeof CATEGORY_COLORS;

export const CATEGORIES: Category[] = ['Work', 'Health', 'Errand', 'Social', 'Travel', 'Other'];

export const FONT = {
  regular: 'Inter-Regular',
  medium:  'Inter-Medium',
  semibold: 'Inter-SemiBold',
  bold:    'Inter-Bold',
  extrabold: 'Inter-ExtraBold',
};

export const RADIUS = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 999,
};

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};
